services:
  aws-ses:
    container_name: aws-ses-v2-local
    hostname: aws-ses-v2-local
    build:
      context: .
    # Uncomment the line below to use the pre-built image instead of building it from the local build context
    # image: ghcr.io/domdomegg/aws-ses-v2-local
    pull_policy: always
    # See .env.example
    environment:
      AWS_SES_ACCOUNT:
      SMTP_TRANSPORT:
    working_dir: /srv/www/dist
    ports:
      - "8005:8005"
    expose:
      - 8005
    networks:
      default:

networks:
  default:
