# This file is centrally managed
# https://github.com/domdomegg/domdomegg/blob/master/file-sync/auto-dependabot.yaml

name: Dependabot automation

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review
      - unlabeled

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot_automation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'do not merge') }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
